### ISSUE TITLE
Flags for bare-metal

### ISSUE THREAD

**Issue by p3p** [platformio/platform-nxplpc#14]
Following the update to 3.4.0 the build does not seem to be using the default bare-metal flags (specifically the F_CPU definition) when using custom build scripts, I assume this is a consequence of moving these to the `_bare.py` file.

This may not be a bug, it could be my extra script (things have changed since it was written), but it has changed default behaviour.

**Comment by ivankravets** [comment]
This is a bug. Thanks for the report! 

@valeros we should add https://github.com/platformio/platform-ststm32/blob/develop/builder/main.py#L76:L77 to each dev/platform where flags were moved to a separate file. I see all mbed compatible dev/platforms are affected.

**Comment by ivankravets** [comment]
Thanks, fixed! Please update platforms via `$ pio update`
