### ISSUE TITLE
libbacktrace could not find executable to open compiling for SKR 1.3 with 2130 drv.

### ISSUE THREAD

**Issue by Unpoor** [platformio/platform-nxplpc#17]
We have written the needed data into your clipboard because it was too large to send. Please 
Issue Type: <b>Bug</b>

In file included from c:\users\unpoo\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\8.2.1\bits\basic_string.h:6400,
                 from c:\users\unpoo\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\8.2.1\string:52,
                 from c:\users\unpoo\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\8.2.1\bits\locale_classes.h:40,
                 from c:\users\unpoo\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\8.2.1\bits\ios_base.h:41,
                 from c:\users\unpoo\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\8.2.1\ios:42,
                 from c:\users\unpoo\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\8.2.1\ostream:38,
                 from c:\users\unpoo\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\8.2.1\iterator:64,
                 from C:\users\unpoo\.platformio\packages\framework-arduino-lpc176x\cores\arduino/pinmapping.h:27,
                 from C:\users\unpoo\.platformio\packages\framework-arduino-lpc176x\cores\arduino/Arduino.h:34,
                 from c:\3dprint\cr10s_m_bugfix2_0_x\marlin\src\hal\shared\marduino.h:35,
                 from Marlin\src\gcode\sdcard\../../inc/../HAL/./HAL_LPC1768/HAL.h:39,
                 from Marlin\src\gcode\sdcard\../../inc/../HAL/HAL.h:26,
                 from Marlin\src\gcode\sdcard\../../inc/MarlinConfig.h:30,
                 from Marlin\src\gcode\sdcard\M23.cpp:23:
c:\users\unpoo\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\8.2.1\ext\string_conversions.h: In instantiation of '_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT*, _CharT**, _Base ...), const char*, const _CharT*, std::size_t*, _Base ...) [with _TRet = long int; _Ret = int; _CharT = char; _Base = {int}; std::size_t = unsigned int]':
c:\users\unpoo\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\8.2.1\bits\basic_string.h:6412:19:   required from here
c:\users\unpoo\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\8.2.1\ext\string_conversions.h:94:5: internal compiler error: Illegal instruction
     }
     ^
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
*** [.pio\build\LPC1768\src\src\gcode\sdcard\M23.cpp.o] Error 1
=================================================================== [ERROR] Took 49.86 seconds ===================================================================

=========================================================================== [SUMMARY] ===========================================================================
Environment megaatmega2560              [IGNORED]
Environment megaatmega1280              [IGNORED]
Environment at90usb1286_cdc             [IGNORED]
Environment at90usb1286_dfu             [IGNORED]
Environment DUE                         [IGNORED]
Environment DUE_USB                     [IGNORED]
Environment DUE_debug                   [IGNORED]
Environment LPC1768                     [FAILED]

Extension version: 1.8.2
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3503)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (3.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>
.

**Comment by ivankravets** [comment]
Please provide a simple project to reproduce this issue.

**Comment by Unpoor** [comment]
Cant reproduse the error cuzz I swapped to VS code.
