### ISSUE TITLE
debug for mbed LPC1768 board

### ISSUE THREAD

**Issue by sstaub** [platformio/platform-nxplpc#3]
can you add debug for the mbed LPC1768 board (and other like LPC800-MAX, LPCXpresso11U68 ... with CMSIS-DAP)

**Comment by ivankravets** [comment]
@valeros please add support and check if these boards are ready for debugging or have "onboard" debugger.

**Comment by ivankravets** [comment]
@sstaub do you have any boards based on LPC1768?

**Comment by sstaub** [comment]
yes, i have a mbed LPC1768 board [()](https://developer.mbed.org/platforms/mbed-LPC1768/) and can test it

**Comment by valeros** [comment]
Hi @sstaub! Would be great if you could test debug with your board! Just Install NXP platform from the development branch:
```
pio platform install https://github.com/platformio/platform-nxplpc/archive/develop.zip
```

**Comment by sstaub** [comment]
I tried to update, but i get always v2.0.0, when I try to debug I get an error that there is no support for the lpc1768
![nxp](https://cloud.githubusercontent.com/assets/6450325/25923277/f9c7a3e0-35dc-11e7-8a65-44e2e2f4c266.png)

**Comment by valeros** [comment]
@sstaub could you try  next steps:
```
pio platform uninstall nxplpc
pio platform install https://github.com/platformio/platform-nxplpc.git
```

**Comment by sstaub** [comment]
now I get following error when starting debugging
![error](https://cloud.githubusercontent.com/assets/6450325/25941332/4f5a887a-3639-11e7-9645-d1e7790d1c55.png)

**Comment by ivankravets** [comment]
Resolved via http://docs.platformio.org/en/latest/plus/debugging.html#pyocd-and-cmsis-dap
