### ISSUE TITLE
UnknownBoard: Unknown board ID 'ubloxc027'

### ISSUE THREAD

**Issue by gigawatts** [platformio/platform-nxplpc#30]
Attempting to setup a project for this board: https://docs.platformio.org/en/stable/boards/nxplpc/ubloxc027.html

I get the error `UnknownBoard: Unknown board ID 'ubloxc027'`

**Comment by valeros** [comment]
Hi @gigawatts, unfortunately, this board is no longer supported mainly because this platform was updated to support the latest mbed v6 which is not compatible with `ubloxc027`. Documentation will be updated accordingly.
