### ISSUE TITLE
Need latest version of the mbed lib but you are still pushing an old one down

### ISSUE THREAD

**Issue by wsnell** [platformio/platform-nxplpc#8]
Need to run the nwer version of the mbed libs to fix the problem with the Tickers going crazy. Current version of mbed c++ libs appears to be 150 vs the laest is 137+
 framework-mbed-4.50701.0 now installed with pio update/upgrade but I think I need framework-mbed-4.50703.4. Why can't you guys use the latest?

I also see what I believe is the newer lib here:
https://bintray.com/platformio/dl-packages/framework-mbed#files

**Comment by ivankravets** [comment]
https://github.com/platformio/platform-nxplpc#development-version

The final release is coming soon.
